version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: eventhub_keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_PROXY_HEADERS: "xforwarded"
    ports:
      - "8080:8080"
    command: start-dev
  redis:
    image: redis:latest
    container_name: eventhub_redis
    ports:
      - "6379:6379"
